[package]
name = "git-tags-rs"
version = "0.1.0"
authors = ["bmcorser <bmcorser@gmail.com>"]

[dependencies]
clap = "0.10"

[lib]
name = "tag"
path = "src/lib/tag.rs"

[[bin]]
name = "tag"
path = "src/bin/main.rs"
