[package]
name = "git-tags-rs"
version = "0.1.0"
authors = ["bmcorser <bmcorser@gmail.com>"]

[dependencies]
clap = "0.10"
tempfile = "0.5"
git2 = "0.2.11"

[lib]
name = "tag"
path = "src/tag/mod.rs"

[[bin]]
name = "tag"
path = "src/cli/main.rs"
